"""
Test suite for the production COLMAP + Screened Poisson Reconstruction pipeline.
Validates:
1. 9-stage StageType enum sequence
2. Poisson meshing module (Screened Poisson -> model.obj, model.ply, model.glb)
3. Viewer candidate resolution priority (model.obj > model.glb > model.ply)
4. Absence of Gaussian Splatting deliverables in scene_manifest.json
5. Verification of generated deliverables in outputs directory
"""

import os
import unittest
from pathlib import Path
import json
import numpy as np
import open3d as o3d

from pipeline.stage import StageType, StageStatus
from pipeline.poisson_mesher import PoissonMesher, PoissonResult
from viewer.obj_viewer import find_obj_file
from config import DEFAULT_CONFIG, DenseConfig, PoissonConfig


class TestColmapPoissonPipeline(unittest.TestCase):

    def test_pipeline_stages_sequence(self):
        """Verify 9 distinct sequential stages."""
        expected_stages = [
            StageType.FRAME_EXTRACTION,
            StageType.FILTER_FRAMES,
            StageType.COLMAP_FEATURES,
            StageType.COLMAP_MATCHING,
            StageType.COLMAP_MAPPER,
            StageType.DENSE_STEREO,
            StageType.STEREO_FUSION,
            StageType.POISSON_MESHING,
            StageType.EXPORT,
        ]
        self.assertEqual(len(expected_stages), 9)
        all_stages = list(StageType)
        for i, exp in enumerate(expected_stages):
            self.assertEqual(all_stages[i], exp)

    def test_config_defaults(self):
        """Verify DenseConfig and PoissonConfig are registered on DEFAULT_CONFIG."""
        self.assertTrue(hasattr(DEFAULT_CONFIG, "dense"))
        self.assertTrue(hasattr(DEFAULT_CONFIG, "poisson"))
        self.assertEqual(DEFAULT_CONFIG.dense.max_image_size, 2000)
        self.assertEqual(DEFAULT_CONFIG.dense.min_num_pixels, 5)
        self.assertEqual(DEFAULT_CONFIG.poisson.depth, 9)
        self.assertEqual(DEFAULT_CONFIG.poisson.density_trim_quantile, 0.05)

    def test_poisson_mesher_synthetic(self):
        """Verify Poisson mesher generates valid OBJ, PLY, and GLB from point cloud with normals."""
        import tempfile
        with tempfile.TemporaryDirectory() as tmp_dir:
            tmp_path = Path(tmp_dir)
            pcd = o3d.geometry.PointCloud()
            mesh_sphere = o3d.geometry.TriangleMesh.create_sphere(radius=1.0, resolution=20)
            pcd.points = mesh_sphere.vertices
            pcd.normals = mesh_sphere.vertex_normals
            pcd.colors = o3d.utility.Vector3dVector(np.ones((len(pcd.points), 3)) * 0.8)

            ply_in = tmp_path / "test_points.ply"
            o3d.io.write_point_cloud(str(ply_in), pcd)

            mesher = PoissonMesher(PoissonConfig(depth=6, density_trim_quantile=0.0))
            res = mesher.run_poisson_reconstruction(ply_in, tmp_path)

            self.assertTrue(res.success)
            self.assertGreater(res.num_triangles, 0)
            self.assertGreater(res.num_vertices, 0)
            self.assertTrue(res.model_obj.exists())
            self.assertTrue(res.model_ply.exists())
            self.assertTrue(res.model_glb.exists())

            with open(res.model_obj, "r") as f:
                content = f.read()
                self.assertIn("f ", content)

    def test_viewer_candidate_priority(self):
        """Verify find_obj_file prioritizes model.obj over model.glb and model.ply."""
        import tempfile
        with tempfile.TemporaryDirectory() as tmp_dir:
            tmp_path = Path(tmp_dir)
            (tmp_path / "model.obj").write_text("v 0 0 0\n")
            (tmp_path / "model.glb").write_text("glb_data")
            (tmp_path / "model.ply").write_text("ply_data")
            (tmp_path / "dense").mkdir()
            (tmp_path / "dense" / "fused.ply").write_text("fused_data")

            best = find_obj_file(tmp_path)
            self.assertIsNotNone(best)
            self.assertEqual(best.name, "model.obj")

            (tmp_path / "model.obj").unlink()
            best2 = find_obj_file(tmp_path)
            self.assertEqual(best2.name, "model.glb")

            (tmp_path / "model.glb").unlink()
            best3 = find_obj_file(tmp_path)
            self.assertEqual(best3.name, "model.ply")

    def test_production_run_deliverables(self):
        """Verify the deliverables generated by the full validation run."""
        outputs_dir = Path("outputs")
        prod_dirs = sorted(outputs_dir.glob("prod_final3_*"))
        if not prod_dirs:
            self.skipTest("No prod_final3 directory found to validate deliverables")

        run_dir = prod_dirs[-1]
        manifest_path = run_dir / "scene_manifest.json"
        self.assertTrue(manifest_path.exists(), "scene_manifest.json must exist")

        with open(manifest_path, "r") as f:
            manifest = json.load(f)

        self.assertEqual(manifest.get("pipeline_status"), "completed")
        self.assertEqual(manifest.get("viewer_model"), "model.obj")
        self.assertIn("dense_reconstruction", manifest)
        self.assertIn("poisson_mesh", manifest)
        self.assertGreater(manifest["poisson_mesh"]["triangles"], 0)
        self.assertGreater(manifest["poisson_mesh"]["vertices"], 0)

        deliverables = manifest.get("deliverables", {})
        self.assertNotIn("gaussian_splat", deliverables)
        self.assertNotIn("splat", deliverables)
        for k, v in deliverables.items():
            self.assertFalse(str(v).endswith(".splat"), f"Unexpected .splat file: {v}")

        obj_file = run_dir / "model.obj"
        ply_file = run_dir / "model.ply"
        glb_file = run_dir / "model.glb"
        fused_ply = run_dir / "dense" / "fused.ply"

        self.assertTrue(obj_file.exists(), "model.obj missing")
        self.assertTrue(ply_file.exists(), "model.ply missing")
        self.assertTrue(glb_file.exists(), "model.glb missing")
        self.assertTrue(fused_ply.exists(), "dense/fused.ply missing")

        with open(obj_file, "r") as f:
            lines = f.readlines()
            face_lines = [l for l in lines if l.startswith("f ")]
            self.assertGreater(len(face_lines), 0, "model.obj must contain triangle faces")


if __name__ == "__main__":
    unittest.main()
